# Generated by Django 4.1.3 on 2022-11-09 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(db_index=True)),
                ("slug", models.SlugField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Actor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(db_index=True)),
                ("slug", models.SlugField()),
                (
                    "movies",
                    models.ManyToManyField(related_name="actors", to="searcher.movie"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
