# Generated by Django 4.1.3 on 2022-11-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=256)),
                ("slug", models.SlugField()),
                ("csfd_id", models.IntegerField(db_index=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Actor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=256)),
                ("slug", models.SlugField()),
                ("csfd_id", models.IntegerField(db_index=True, null=True)),
                (
                    "movies",
                    models.ManyToManyField(related_name="actors", to="searcher.movie"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
