# Generated by Django 4.1.3 on 2022-11-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("searcher", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="actor",
            name="csfd_id",
            field=models.TextField(db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="csfd_id",
            field=models.TextField(db_index=True, default=None, null=True),
        ),
    ]
